apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scl-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Object
      object:
        metric:
          name: requests-per-second
        describedObject:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: pgtic-ingress
        target:
          type: Value
          value: 10
  behavior:
    scaleDown:
      selectPolicy: Min
      stabilizationWindowSeconds: 30
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 30
