apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dpl
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pgtic/frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend-svc

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: frontend
---

apiVersion: autoscaling/v2

kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-dpl
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      selectPolicy: Min
      stabilizationWindowSeconds: 30
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 30
